### PR TITLE
Added the prefer-source option

### PR DESCRIPTION
**Pull request by EmanueleMinotto**
Currently the Appveyor test loses time trying to download the distribution version of every package, using the `--prefer-source` option this should be fixed.

### CODE REVIEW

**Comment by webmozart** [comment]
How could a Git checkout possibly be faster than downloading a dist version? It seems that the last build on AppVeyor was about twice as slow as the previous one.

**Comment by EmanueleMinotto** [comment]
Because without the explicit option Composer try to download the dependencies using the dist ([ref](https://getcomposer.org/doc/03-cli.md#install)), but after a number of requests [this problem comes out](https://ci.appveyor.com/project/webmozart/silex-provider/build/1.0.34/job/ngd0tv6s0nltefd1#L256).

To prevent it there are only the Appveyor secure env token possibility or the `--prefer-source` option, both of them are faster than "failed dist download + source download".

**Comment by webmozart** [comment]
Ah I see. I suppose we should do this everywhere then?

**Comment by EmanueleMinotto** [comment]
@webmozart yes, and currently missing this I see:
- this repo's appveyor.yml (so this PR to complete)
- puli/gulp-plugin
- puli/symfony-bridge
- puli/symfony-bundle
- puli/twig-extension

**Comment by webmozart** [comment]
Thanks for the research! Can you open a ticket please?

**Comment by webmozart** [comment]
see https://github.com/puli/issues/issues/169

**Pull request closed without merging**
